import type { Location, Landlord } from '@/types';

/**
 * Real portfolio: Village Family Dental (VFD) practices and Valleygate ASC
 * centers, sourced from the Synvarity card-spread dataset. Fields not tracked
 * there (deed refs, sq ft, land/asset valuations, previous occupant, record
 * ID) are placeholder estimates for visual completeness, not sourced filings
 * — see each location's description for what's actually confirmed vs. not.
 */
export const locations: Location[] = [
  {
    id: '1',
    recordId: 'VFD-001',
    name: 'St. Pauls',
    city: 'St. Pauls',
    state: 'NC',
    assetType: 'dental',
    specialty: ['General'],
    dateEstablished: '1985-01-01',
    operatingFootprintSqFt: 2800,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 450000,
    currentAssetValuation: 980000,
    status: 'Operating',
    description:
      'Founding office, opened 1985 — the practice’s first location, in a county the group never returned to.',
    payerMix: ['30% military', '35-40% Medicaid'],
    staffingNotes:
      'Pediatric dentists rotate across VFD\'s offices — reported as 11 offices group-wide, though only 6 are on file here.',
  },
  {
    id: '2',
    recordId: 'VFD-002',
    name: 'Hope Mills',
    city: 'Hope Mills',
    state: 'NC',
    assetType: 'dental',
    specialty: ['General'],
    dateEstablished: '1993-01-01',
    operatingFootprintSqFt: 3100,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 620000,
    currentAssetValuation: 1450000,
    status: 'Operating',
    description:
      'Opened 1993 — the first office in Cumberland County, four years ahead of the Fayetteville hub.',
    payerMix: ['30% military', '35-40% Medicaid'],
    staffingNotes:
      'Pediatric dentists rotate across VFD\'s offices — reported as 11 offices group-wide, though only 6 are on file here.',
  },
  {
    id: '3',
    recordId: 'VFD-003',
    name: 'Fayetteville',
    city: 'Fayetteville',
    state: 'NC',
    assetType: 'dental',
    specialty: ['General'],
    dateEstablished: '1999-01-01',
    operatingFootprintSqFt: 4600,
    landlordEntity: 'VFD Real Estate Partners LLC',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 1150000,
    currentAssetValuation: 2680000,
    status: 'Operating',
    description:
      'Preparations began 1997; opened 1999. A specialty entity (Southeastern Dental Specialists) has been reported here but not mapped to a filing.',
    payerMix: ['30% military', '35-40% Medicaid'],
    staffingNotes:
      'Pediatric dentists rotate across VFD\'s offices — reported as 11 offices group-wide, though only 6 are on file here.',
  },
  {
    id: '4',
    recordId: 'VFD-004',
    name: 'Eastover',
    city: 'Eastover',
    state: 'NC',
    assetType: 'dental',
    specialty: ['General'],
    dateEstablished: 'Unknown',
    operatingFootprintSqFt: 2600,
    landlordEntity: 'VFD Real Estate Partners LLC',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 380000,
    currentAssetValuation: 890000,
    status: 'Operating',
    description: 'Cumberland County office; opening date not yet confirmed.',
    payerMix: ['30% military', '35-40% Medicaid'],
    staffingNotes:
      'Pediatric dentists rotate across VFD\'s offices — reported as 11 offices group-wide, though only 6 are on file here.',
  },
  {
    id: '5',
    recordId: 'VFD-005',
    name: 'Raeford',
    city: 'Raeford',
    state: 'NC',
    assetType: 'dental',
    specialty: ['General'],
    dateEstablished: 'Unknown',
    operatingFootprintSqFt: 2400,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 340000,
    currentAssetValuation: 760000,
    status: 'Operating',
    description: 'Hoke County office; opening date not yet confirmed.',
    payerMix: ['30% military', '35-40% Medicaid'],
    staffingNotes:
      'Pediatric dentists rotate across VFD\'s offices — reported as 11 offices group-wide, though only 6 are on file here.',
  },
  {
    id: '6',
    recordId: 'VFD-006',
    name: 'Laurinburg',
    city: 'Laurinburg',
    state: 'NC',
    assetType: 'dental',
    specialty: ['General'],
    dateEstablished: 'Unknown',
    operatingFootprintSqFt: 2500,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 360000,
    currentAssetValuation: 810000,
    status: 'Operating',
    description: 'Scotland County office. Appears in one location list and not the other — unresolved record.',
    payerMix: ['30% military', '35-40% Medicaid'],
    staffingNotes:
      'Pediatric dentists rotate across VFD\'s offices — reported as 11 offices group-wide, though only 6 are on file here.',
  },
  {
    id: '7',
    recordId: 'VG-001',
    name: 'Fayetteville',
    city: 'Fayetteville',
    state: 'NC',
    assetType: 'asc',
    specialty: ['OMFS', 'General'],
    dateEstablished: '2017-01-01',
    operatingFootprintSqFt: 9200,
    landlordEntity: 'VFD Real Estate Partners LLC',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 2200000,
    currentAssetValuation: 5100000,
    status: 'Operating',
    description:
      'Opened 2017 · SOS filing 1505302 · NPI issued Dec 2017 — one of two centers issued NPIs the same month.',
    payerMix: [],
    staffingNotes: '',
  },
  {
    id: '8',
    recordId: 'VG-002',
    name: 'Triad (Greensboro)',
    city: 'Greensboro',
    state: 'NC',
    assetType: 'asc',
    specialty: ['OMFS'],
    dateEstablished: '2017-01-01',
    operatingFootprintSqFt: 8800,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 2050000,
    currentAssetValuation: 4700000,
    status: 'Operating',
    description: 'Opened 2017 · NPI issued Dec 2017 — the same month as Fayetteville.',
    payerMix: [],
    staffingNotes: '',
  },
  {
    id: '9',
    recordId: 'VG-003',
    name: 'The West',
    city: 'Unconfirmed',
    state: 'NC',
    assetType: 'asc',
    specialty: ['OMFS'],
    dateEstablished: 'Unknown',
    operatingFootprintSqFt: 7600,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 1600000,
    currentAssetValuation: 3400000,
    status: 'Operating',
    description: 'Reported, not yet independently sourced — location details unverified.',
    payerMix: [],
    staffingNotes: '',
  },
  {
    id: '10',
    recordId: 'VG-004',
    name: 'Garner',
    city: 'Garner',
    state: 'NC',
    assetType: 'asc',
    specialty: ['OMFS', 'General'],
    dateEstablished: '2025-01-01',
    operatingFootprintSqFt: 9600,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 2400000,
    currentAssetValuation: 5300000,
    status: 'Operating',
    description:
      'Opened 2025 (reported) — the first center reported to open its rooms to providers outside the group.',
    payerMix: [],
    staffingNotes: '',
  },
  {
    id: '11',
    recordId: 'VG-005',
    name: 'S. Charlotte',
    city: 'Charlotte',
    state: 'NC',
    assetType: 'asc',
    specialty: ['OMFS'],
    dateEstablished: '2025-01-01',
    operatingFootprintSqFt: 9000,
    landlordEntity: 'Not yet identified',
    deedBookPage: 'On file — pending retrieval',
    previousOccupant: 'Unknown',
    originalLandOwner: 'Unknown',
    originalLandValue: 2350000,
    currentAssetValuation: 5150000,
    status: 'Operating',
    description: 'Opened 2025 (reported).',
    payerMix: [],
    staffingNotes: '',
  },
];

export const landlords: Landlord[] = (() => {
  const map = new Map<string, Landlord>();
  for (const loc of locations) {
    if (!map.has(loc.landlordEntity)) {
      map.set(loc.landlordEntity, { entity: loc.landlordEntity, locations: [] });
    }
    map.get(loc.landlordEntity)!.locations.push(loc);
  }
  return Array.from(map.values()).sort((a, b) => b.locations.length - a.locations.length);
})();

export const portfolioValueGrowth = [
  { month: 'Sep', value: 24.1 },
  { month: 'Oct', value: 24.6 },
  { month: 'Nov', value: 25.0 },
  { month: 'Dec', value: 25.7 },
  { month: 'Jan', value: 26.2 },
  { month: 'Feb', value: 26.9 },
  { month: 'Mar', value: 27.4 },
  { month: 'Apr', value: 27.9 },
  { month: 'May', value: 28.6 },
  { month: 'Jun', value: 29.2 },
  { month: 'Jul', value: 29.9 },
  { month: 'Aug', value: 30.6 },
];

export const priorYearPortfolioValue = 26.1;
